### PR TITLE
Add dry-run,no-color,with-breakpoints,continue-on-error functionality

### PR DESCRIPTION
**Pull request by karampok**
As part of me using the library for demos, I had to modify the library code to add the following functions

```
--dry-run                     run the demo and only prints the commands (default: true)
--no-color                    run the demo and output to be without colors (default: false)
--with-breakpoints            breakpoint (default: false)
--continue-on-error           continue if there a step fails (default: false)
```
This is a fully draft PR. In case you want, I can work towards  improving the code for merging. Thanks

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Cool, thank you!

**Comment by saschagrunert** [comment]
@karampok do you mind a rebase?

**Comment by karampok** [comment]
Is there anything more from my side?

**Review by saschagrunert — APPROVED** [review]
Thanks!

**Comment by karampok** [comment]
cool, thanks!

**Comment by saschagrunert** [comment]
We may wanna update the README.md documentation, though.

**Pull request merged**
